# Generated by Django 6.0.1 on 2026-01-24 21:04

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du jury')),
                ('statut', models.CharField(choices=[('PROPOSE', 'Proposé'), ('VALIDE', 'Validé'), ('ACTIF', 'Actif')], default='PROPOSE', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Jurys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('batiment', models.CharField(max_length=100, verbose_name='Bâtiment')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CANDIDAT', 'Candidat'), ('ENSEIGNANT', 'Enseignant')], default='CANDIDAT', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidatProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('cycle', models.CharField(choices=[('INGENIEUR', 'Ingénieur'), ('SCIENCE_INGENIEUR', "Science de l'ingénieur"), ('MASTER_PRO', 'Master professionnel')], default='INGENIEUR', max_length=30, verbose_name='Cycle')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/candidats/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='candidat_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='app_soutenance.departement', verbose_name='Département')),
            ],
            options={
                'verbose_name': 'Profil Candidat',
                'verbose_name_plural': 'Profils Candidats',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='DossierSoutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_memoire', models.CharField(max_length=300, verbose_name='Titre du mémoire')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('DEPOSE', 'Déposé'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaires_admin', models.TextField(blank=True, verbose_name='Commentaires admin')),
                ('demande_suppression', models.BooleanField(default=False, verbose_name='Demande de suppression')),
                ('commentaire_suppression', models.TextField(blank=True, verbose_name='Commentaire suppression')),
                ('date_demande_suppression', models.DateTimeField(blank=True, null=True, verbose_name='Date demande suppression')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='app_soutenance.candidatprofile', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Dossier de Soutenance',
                'verbose_name_plural': 'Dossiers de Soutenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du document')),
                ('fichier', models.FileField(upload_to='documents/', verbose_name='Fichier')),
                ('type_piece', models.CharField(choices=[('MEMOIRE', 'Mémoire'), ('RECU_PAIEMENT', 'Reçu de paiement'), ('ACCORD_STAGE', 'Accord de stage'), ('LETTRE_MISE_EN_STAGE', 'Lettre de mise en stage'), ('CERTIFICAT_SCOLARITE', 'Certificat de scolarité'), ('ATTESTATION', 'Attestation'), ('AUTRE', 'Autre')], max_length=30, verbose_name='Type de pièce')),
                ('est_obligatoire', models.BooleanField(default=False, verbose_name='Obligatoire')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app_soutenance.dossiersoutenance', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('PROFESSEUR', 'Professeur'), ('MAITRE_CONF', 'Maître de Conférence'), ('CHARGE_COURS', 'Chargé de Cours'), ('ASSISTANT', 'Assistant')], max_length=20, verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('departements', models.ManyToManyField(related_name='enseignants', to='app_soutenance.departement', verbose_name='Départements')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Enseignant',
                'verbose_name_plural': 'Profils Enseignants',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='encadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_encadres', to='app_soutenance.enseignantprofile', verbose_name='Encadreur'),
        ),
        migrations.CreateModel(
            name='MembreJury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('PRESIDENT', 'Président'), ('RAPPORTEUR', 'Rapporteur'), ('ENCADREUR', 'Encadreur'), ('EXAMINATEUR', 'Examinateur')], max_length=20, verbose_name='Rôle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_jury', to='app_soutenance.enseignantprofile', verbose_name='Enseignant')),
                ('jury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='app_soutenance.jury', verbose_name='Jury')),
            ],
            options={
                'verbose_name': 'Membre du Jury',
                'verbose_name_plural': 'Membres du Jury',
                'ordering': ['role', 'enseignant__user__last_name'],
                'unique_together': {('jury', 'enseignant', 'role')},
            },
        ),
        migrations.AddField(
            model_name='jury',
            name='membres',
            field=models.ManyToManyField(related_name='jurys', through='app_soutenance.MembreJury', to='app_soutenance.enseignantprofile', verbose_name='Membres du jury'),
        ),
        migrations.CreateModel(
            name='SessionSoutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('date_ouverture', models.DateTimeField(verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateTimeField(verbose_name='Date de clôture')),
                ('niveau_concerne', models.CharField(max_length=20, verbose_name='Niveau concerné')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('FERME', 'Fermé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Session de Soutenance',
                'verbose_name_plural': 'Sessions de Soutenance',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.AddField(
            model_name='jury',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurys', to='app_soutenance.sessionsoutenance', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='app_soutenance.sessionsoutenance', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure')),
                ('duree_minutes', models.IntegerField(default=45, verbose_name='Durée (minutes)')),
                ('ordre_passage', models.IntegerField(blank=True, null=True, verbose_name='Ordre de passage')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='app_soutenance.dossiersoutenance', verbose_name='Dossier')),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances', to='app_soutenance.jury', verbose_name='Jury')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances', to='app_soutenance.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Soutenance',
                'verbose_name_plural': 'Soutenances',
                'ordering': ['date_heure', 'ordre_passage'],
            },
        ),
    ]
