# Generated by Django 5.2.4 on 2025-12-09 20:31

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('batiment', models.CharField(max_length=100, verbose_name='Bâtiment')),
                ('capacite', models.IntegerField(verbose_name='Capacité')),
                ('equipements', models.JSONField(blank=True, default=list, help_text='Liste des équipements disponibles', verbose_name='Équipements')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['batiment', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrateur'), ('CANDIDAT', 'Candidat'), ('ENSEIGNANT', 'Enseignant')], default='CANDIDAT', max_length=20, verbose_name='Rôle')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidatProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50, unique=True, verbose_name='Matricule')),
                ('niveau_etude', models.CharField(choices=[('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat')], max_length=20, verbose_name="Niveau d'étude")),
                ('filiere', models.CharField(max_length=100, verbose_name='Filière')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/candidats/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidat_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Candidat',
                'verbose_name_plural': 'Profils Candidats',
                'ordering': ['matricule'],
            },
        ),
        migrations.CreateModel(
            name='DossierSoutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre_memoire', models.CharField(max_length=300, verbose_name='Titre du mémoire')),
                ('theme', models.CharField(max_length=200, verbose_name='Thème')),
                ('memoire_pdf', models.FileField(blank=True, null=True, upload_to='memoires/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Mémoire PDF')),
                ('annexes', models.JSONField(blank=True, default=list, help_text='Liste des fichiers annexes', verbose_name='Annexes')),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('DEPOSE', 'Déposé'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='BROUILLON', max_length=20, verbose_name='Statut')),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('commentaires_admin', models.TextField(blank=True, verbose_name='Commentaires admin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='app_soutenance.candidatprofile', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Dossier de Soutenance',
                'verbose_name_plural': 'Dossiers de Soutenance',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('est_interne', models.BooleanField(default=False, help_text='Visible seulement par admin et encadreur', verbose_name='Interne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='app_soutenance.dossiersoutenance', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnseignantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(choices=[('PROFESSEUR', 'Professeur'), ('MAITRE_CONF', 'Maître de Conférence'), ('CHARGE_COURS', 'Chargé de Cours'), ('ASSISTANT', 'Assistant')], max_length=20, verbose_name='Grade')),
                ('departement', models.CharField(max_length=100, verbose_name='Département')),
                ('specialite', models.CharField(max_length=100, verbose_name='Spécialité')),
                ('disponibilites', models.JSONField(blank=True, default=dict, help_text='Format JSON pour les disponibilités de planification', verbose_name='Disponibilités')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil Enseignant',
                'verbose_name_plural': 'Profils Enseignants',
                'ordering': ['user__last_name'],
            },
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='encadreur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_encadres', to='app_soutenance.enseignantprofile', verbose_name='Encadreur'),
        ),
        migrations.CreateModel(
            name='FichierAnnexe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du fichier')),
                ('fichier', models.FileField(upload_to='annexes/', verbose_name='Fichier')),
                ('type_document', models.CharField(choices=[('ATTESTATION', 'Attestation'), ('FICHE_EVAL', "Fiche d'évaluation"), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type de document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploadé le')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers_annexes', to='app_soutenance.dossiersoutenance', verbose_name='Dossier')),
            ],
            options={
                'verbose_name': 'Fichier Annexe',
                'verbose_name_plural': 'Fichiers Annexes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionSoutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('annee_academique', models.CharField(max_length=20, verbose_name='Année académique')),
                ('date_ouverture', models.DateTimeField(verbose_name="Date d'ouverture")),
                ('date_cloture', models.DateTimeField(verbose_name='Date de clôture')),
                ('niveau_concerne', models.CharField(max_length=20, verbose_name='Niveau concerné')),
                ('statut', models.CharField(choices=[('OUVERT', 'Ouvert'), ('FERME', 'Fermé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé')], default='OUVERT', max_length=20, verbose_name='Statut')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Session de Soutenance',
                'verbose_name_plural': 'Sessions de Soutenance',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du jury')),
                ('statut', models.CharField(choices=[('PROPOSE', 'Proposé'), ('VALIDE', 'Validé'), ('ACTIF', 'Actif')], default='PROPOSE', max_length=20, verbose_name='Statut')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('examinateurs', models.ManyToManyField(blank=True, related_name='jurys_examines', to='app_soutenance.enseignantprofile', verbose_name='Examinateurs')),
                ('president', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurys_presides', to='app_soutenance.enseignantprofile', verbose_name='Président')),
                ('rapporteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jurys_rapportes', to='app_soutenance.enseignantprofile', verbose_name='Rapporteur')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jurys', to='app_soutenance.sessionsoutenance', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Jury',
                'verbose_name_plural': 'Jurys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossiers', to='app_soutenance.sessionsoutenance', verbose_name='Session'),
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_heure', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure')),
                ('duree_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('ordre_passage', models.IntegerField(blank=True, null=True, verbose_name='Ordre de passage')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('note_finale', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Note finale')),
                ('mention', models.CharField(blank=True, choices=[('PASSABLE', 'Passable'), ('ASSEZ_BIEN', 'Assez Bien'), ('BIEN', 'Bien'), ('TRES_BIEN', 'Très Bien'), ('EXCELLENT', 'Excellent')], max_length=20, null=True, verbose_name='Mention')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('pv_genere', models.BooleanField(default=False, verbose_name='PV généré')),
                ('pv_file', models.FileField(blank=True, null=True, upload_to='pv/', verbose_name='Fichier PV')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('dossier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='app_soutenance.dossiersoutenance', verbose_name='Dossier')),
                ('jury', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances', to='app_soutenance.jury', verbose_name='Jury')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances', to='app_soutenance.salle', verbose_name='Salle')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soutenances', to='app_soutenance.sessionsoutenance', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Soutenance',
                'verbose_name_plural': 'Soutenances',
                'ordering': ['date_heure', 'ordre_passage'],
            },
        ),
        migrations.CreateModel(
            name='ProcesVerbal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_pv', models.CharField(max_length=50, unique=True, verbose_name='Numéro PV')),
                ('contenu', models.TextField(verbose_name='Contenu')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('fichier_pdf', models.FileField(upload_to='pv/', verbose_name='Fichier PDF')),
                ('signatures_jury', models.JSONField(blank=True, default=dict, help_text='Format: {president: true/false, rapporteur: true/false, ...}', verbose_name='Signatures du jury')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('soutenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proces_verbal', to='app_soutenance.soutenance', verbose_name='Soutenance')),
            ],
            options={
                'verbose_name': 'Procès-Verbal',
                'verbose_name_plural': 'Procès-Verbaux',
                'ordering': ['-date_generation'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CONVOCATION', 'Convocation'), ('RAPPEL', 'Rappel'), ('MODIFICATION', 'Modification'), ('INFO', 'Information'), ('VALIDATION', 'Validation')], max_length=20, verbose_name='Type')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('soutenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='app_soutenance.soutenance', verbose_name='Soutenance')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_memoire', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note mémoire (/20)')),
                ('note_presentation', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note présentation (/20)')),
                ('note_reponses', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Note réponses (/20)')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('date_evaluation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('evaluateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app_soutenance.enseignantprofile', verbose_name='Évaluateur')),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='app_soutenance.soutenance', verbose_name='Soutenance')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
                'unique_together': {('soutenance', 'evaluateur')},
            },
        ),
    ]
