# Generated by Django 6.0.1 on 2026-02-09 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soutenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('REPO_CLICK', 'Clic repo GitHub'), ('PAGE_VIEW', 'Vue de page')], max_length=20)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Événement site',
                'verbose_name_plural': 'Événements site',
                'ordering': ['-created_at'],
            },
        ),
    ]
