# Generated by Django 5.2.4 on 2025-12-11 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soutenance', '0002_alter_evaluation_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['nom'],
            },
        ),
        migrations.RemoveField(
            model_name='candidatprofile',
            name='filiere',
        ),
        migrations.RemoveField(
            model_name='enseignantprofile',
            name='departement',
        ),
        migrations.AddField(
            model_name='candidatprofile',
            name='departement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='candidats', to='app_soutenance.departement', verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='enseignantprofile',
            name='departements',
            field=models.ManyToManyField(related_name='enseignants', to='app_soutenance.departement', verbose_name='Départements'),
        ),
    ]
