# Generated by Django 5.2.4 on 2025-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soutenance', '0003_departement_remove_candidatprofile_filiere_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatprofile',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='dossiersoutenance',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='enseignantprofile',
            name='disponibilites',
        ),
        migrations.RemoveField(
            model_name='enseignantprofile',
            name='specialite',
        ),
        migrations.RemoveField(
            model_name='salle',
            name='equipements',
        ),
        migrations.RemoveField(
            model_name='soutenance',
            name='session',
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='commentaire_suppression',
            field=models.TextField(blank=True, verbose_name='Commentaire suppression'),
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='date_demande_suppression',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date demande suppression'),
        ),
        migrations.AddField(
            model_name='dossiersoutenance',
            name='demande_suppression',
            field=models.BooleanField(default=False, verbose_name='Demande de suppression'),
        ),
        migrations.AlterField(
            model_name='soutenance',
            name='duree_minutes',
            field=models.IntegerField(default=45, verbose_name='Durée (minutes)'),
        ),
    ]
