# Generated by Django 5.2.4 on 2025-12-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_soutenance', '0004_remove_candidatprofile_specialite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatprofile',
            name='niveau_etude',
        ),
        migrations.AddField(
            model_name='candidatprofile',
            name='cycle',
            field=models.CharField(choices=[('INGENIEUR', 'Ingénieur'), ('SCIENCE_INGENIEUR', "Science de l'ingénieur"), ('MASTER_PRO', 'Master professionnel')], default='INGENIEUR', max_length=30, verbose_name='Cycle'),
        ),
    ]
